<?php

use Illuminate\Database\Seeder;
use App\Models\Config\Departamento_municipio as Departamento;

class DepartamentosSeeder extends Seeder{

   public function run(){

      #carga de municipio, codigo de depto != 0 es municipio
      $departamentos = [
         ['codigo'=> '1', 'region' => 'Metropolitana', 'codigo_depto' => 0, 'nombre' => 'Guatemala'],
         ['codigo'=> '2', 'region' => 'Nororiente',    'codigo_depto' => 0, 'nombre' => 'El Progreso'],
         ['codigo'=> '3', 'region' => 'Central',       'codigo_depto' => 0, 'nombre' => 'Sacatepéquez'],
         ['codigo'=> '4', 'region' => 'Central',       'codigo_depto' => 0, 'nombre' => 'Chimaltenango'],
         ['codigo'=> '5', 'region' => 'Central',       'codigo_depto' => 0, 'nombre' => 'Escuintla'],
         ['codigo'=> '6', 'region' => 'Suroriente',    'codigo_depto' => 0, 'nombre' => 'Santa Rosa'],
         ['codigo'=> '7', 'region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'Sololá'],
         ['codigo'=> '8', 'region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'Totonicapán'],
         ['codigo'=> '9', 'region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'Quetzaltenango'],
         ['codigo'=> '10','region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'Suchitepéquez'],
         ['codigo'=> '11','region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'Retalhuleu'],
         ['codigo'=> '12','region' => 'Suroccidente',  'codigo_depto' => 0, 'nombre' => 'San Marcos'],
         ['codigo'=> '13','region' => 'Noroccidente',  'codigo_depto' => 0, 'nombre' => 'Huehuetenango'],
         ['codigo'=> '14','region' => 'Noroccidente',  'codigo_depto' => 0, 'nombre' => 'Quiché'],
         ['codigo'=> '15','region' => 'Norte',         'codigo_depto' => 0, 'nombre' => 'Baja Verapaz'],
         ['codigo'=> '16','region' => 'Norte',         'codigo_depto' => 0, 'nombre' => 'Alta Verapaz'],
         ['codigo'=> '17','region' => 'Petén',         'codigo_depto' => 0, 'nombre' => 'Petén'],
         ['codigo'=> '18','region' => 'Nororiente',    'codigo_depto' => 0, 'nombre' => 'Izabal'],
         ['codigo'=> '19','region' => 'Nororiente',    'codigo_depto' => 0, 'nombre' => 'Zacapa'],
         ['codigo'=> '20','region' => 'Nororiente',    'codigo_depto' => 0, 'nombre' => 'Chiquimula'],
         ['codigo'=> '21','region' => 'Suroriente',    'codigo_depto' => 0, 'nombre' => 'Jalapa'],
         ['codigo'=> '22','region' => 'Suroriente',    'codigo_depto' => 0, 'nombre' => 'Jutiapa'],
         ['codigo'=> '0101', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Guatemala'],
         ['codigo'=> '0102', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Santa Catarina Pinula'],
         ['codigo'=> '0103', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San José Pinula'],
         ['codigo'=> '0104', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San José del Golfo'],
         ['codigo'=> '0105', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Palencia'],
         ['codigo'=> '0106', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Chinautla'],
         ['codigo'=> '0107', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San Pedro Ayampuc'],
         ['codigo'=> '0108', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Mixco'],
         ['codigo'=> '0109', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San Pedro Sacatepéquez'],
         ['codigo'=> '0110', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San Juan Sacatepéquez'],
         ['codigo'=> '0111', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'San Raymundo'],
         ['codigo'=> '0112', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Chuarrancho'],
         ['codigo'=> '0113', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Fraijanes'],
         ['codigo'=> '0114', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Amatitlán'],
         ['codigo'=> '0115', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Villa Nueva'],
         ['codigo'=> '0116', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Villa Canales'],
         ['codigo'=> '0117', 'region' => '', 'codigo_depto' => '1', 'nombre' => 'Petapa'],
         ['codigo'=> '0201', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'Guastatoya'],
         ['codigo'=> '0202', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'Morazán'],
         ['codigo'=> '0203', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'San Agustín Acasaguastlán'],
         ['codigo'=> '0204', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'San Cristóbal Acasaguastlán'],
         ['codigo'=> '0205', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'El Jícaro'],
         ['codigo'=> '0206', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'Sansare'],
         ['codigo'=> '0207', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'Sanarate'],
         ['codigo'=> '0208', 'region' => '', 'codigo_depto' => '2', 'nombre' => 'San Antonio la Paz'],
         ['codigo'=> '0301', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Antigua Guatemala'],
         ['codigo'=> '0302', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Jocotenango'],
         ['codigo'=> '0303', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Pastores'],
         ['codigo'=> '0304', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Sumpango'],
         ['codigo'=> '0305', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Santo Domingo Xenacoj'],
         ['codigo'=> '0306', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Santiago Sacatepéquez'],
         ['codigo'=> '0307', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'San Bartolomé Milpas Altas'],
         ['codigo'=> '0308', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'San Lucas Sacatepéquez'],
         ['codigo'=> '0309', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Santa Lucía Milpas Altas'],
         ['codigo'=> '0310', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Magdalena Milpas Altas'],
         ['codigo'=> '0311', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Santa María de Jesús'],
         ['codigo'=> '0312', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Ciudad Vieja'],
         ['codigo'=> '0313', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'San Miguel Dueñas'],
         ['codigo'=> '0314', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Alotenango'],
         ['codigo'=> '0315', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'San Antonio Aguas Calientes'],
         ['codigo'=> '0316', 'region' => '', 'codigo_depto' => '3', 'nombre' => 'Santa Catarina Barahona'],
         ['codigo'=> '0401', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Chimaltenango'],
         ['codigo'=> '0402', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'San José Poaquil'],
         ['codigo'=> '0403', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'San Martín Jilotepeque'],
         ['codigo'=> '0404', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Comalapa'],
         ['codigo'=> '0405', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Santa Apolonia'],
         ['codigo'=> '0406', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Tecpán Guatemala'],
         ['codigo'=> '0407', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Patzún'],
         ['codigo'=> '0408', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Pochuta'],
         ['codigo'=> '0409', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Patzicía'],
         ['codigo'=> '0410', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Santa Cruz Balanyá'],
         ['codigo'=> '0411', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Acatenango'],
         ['codigo'=> '0412', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Yepocapa'],
         ['codigo'=> '0413', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'San Andrés Itzapa'],
         ['codigo'=> '0414', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Parramos'],
         ['codigo'=> '0415', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'Zaragoza'],
         ['codigo'=> '0416', 'region' => '', 'codigo_depto' => '4', 'nombre' => 'El Tejar'],
         ['codigo'=> '0501', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Escuintla'],
         ['codigo'=> '0502', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Santa Lucía Cotzumalguapa'],
         ['codigo'=> '0503', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'La Democracia'],
         ['codigo'=> '0504', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Siquinalá'],
         ['codigo'=> '0505', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Masagua'],
         ['codigo'=> '0506', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Tiquisate'],
         ['codigo'=> '0507', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'La Gomera'],
         ['codigo'=> '0508', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Guanagazapa'],
         ['codigo'=> '0509', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'San José'],
         ['codigo'=> '0510', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Iztapa'],
         ['codigo'=> '0511', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Palín'],
         ['codigo'=> '0512', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'San Vicente Pacaya'],
         ['codigo'=> '0513', 'region' => '', 'codigo_depto' => '5', 'nombre' => 'Nueva Concepción'],
         ['codigo'=> '0601', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Cuilapa'],
         ['codigo'=> '0602', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Barberena'],
         ['codigo'=> '0603', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Santa Rosa de Lima'],
         ['codigo'=> '0604', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Casillas'],
         ['codigo'=> '0605', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'San Rafael las Flores'],
         ['codigo'=> '0606', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Oratorio'],
         ['codigo'=> '0607', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'San Juan Tecuaco'],
         ['codigo'=> '0608', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Chiquimulilla'],
         ['codigo'=> '0609', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Taxisco'],
         ['codigo'=> '0610', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Santa María Ixhuatán'],
         ['codigo'=> '0611', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Guazacapán'],
         ['codigo'=> '0612', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Santa Cruz Naranjo'],
         ['codigo'=> '0613', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Pueblo Nuevo Viñas'],
         ['codigo'=> '0614', 'region' => '', 'codigo_depto' => '6', 'nombre' => 'Nueva Santa Rosa'],
         ['codigo'=> '0701', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Sololá'],
         ['codigo'=> '0702', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San José Chacayá'],
         ['codigo'=> '0703', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa María Visitación'],
         ['codigo'=> '0704', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa Lucía Utatlán'],
         ['codigo'=> '0705', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Nahualá'],
         ['codigo'=> '0706', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa Catarina Ixtahuacán'],
         ['codigo'=> '0707', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa Clara la Laguna'],
         ['codigo'=> '0708', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Concepción'],
         ['codigo'=> '0709', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Andrés Semetabaj'],
         ['codigo'=> '0710', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Panajachel'],
         ['codigo'=> '0711', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa Catarina Palopó'],
         ['codigo'=> '0712', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Antonio Palopó'],
         ['codigo'=> '0713', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Lucas Tolimán'],
         ['codigo'=> '0714', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santa Cruz la Laguna'],
         ['codigo'=> '0715', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Pablo la Laguna'],
         ['codigo'=> '0716', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Marcos la Laguna'],
         ['codigo'=> '0717', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Juan la Laguna'],
         ['codigo'=> '0718', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'San Pedro la Laguna'],
         ['codigo'=> '0719', 'region' => '', 'codigo_depto' => '7', 'nombre' => 'Santiago Atitlán'],
         ['codigo'=> '0801', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'Totonicapán'],
         ['codigo'=> '0802', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'San Cristóbal Totonicapán'],
         ['codigo'=> '0803', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'San Francisco el Alto'],
         ['codigo'=> '0804', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'San Andrés Xecul'],
         ['codigo'=> '0805', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'Momostenango'],
         ['codigo'=> '0806', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'Santa María Chiquimula'],
         ['codigo'=> '0807', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'Santa Lucía la Reforma'],
         ['codigo'=> '0808', 'region' => '', 'codigo_depto' => '8', 'nombre' => 'San Bartolo'],
         ['codigo'=> '0901', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Quetzaltenango'],
         ['codigo'=> '0902', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Salcajá'],
         ['codigo'=> '0903', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Olintepeque'],
         ['codigo'=> '0904', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'San Carlos Sija'],
         ['codigo'=> '0905', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Sibilia'],
         ['codigo'=> '0906', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Cabricán'],
         ['codigo'=> '0907', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Cajolá'],
         ['codigo'=> '0908', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'San Miguel Siguilá'],
         ['codigo'=> '0909', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Ostuncalco'],
         ['codigo'=> '0910', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'San Mateo'],
         ['codigo'=> '0911', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Concepción Chiquirichapa'],
         ['codigo'=> '0912', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'San Martín Sacatepéquez'],
         ['codigo'=> '0913', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Almolonga'],
         ['codigo'=> '0914', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Cantel'],
         ['codigo'=> '0915', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Huitán'],
         ['codigo'=> '0916', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Zunil'],
         ['codigo'=> '0917', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Colomba'],
         ['codigo'=> '0918', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'San Francisco la Unión'],
         ['codigo'=> '0919', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'El Palmar'],
         ['codigo'=> '0920', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Coatepeque'],
         ['codigo'=> '0921', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Génova'],
         ['codigo'=> '0922', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Flores Costa Cuca'],
         ['codigo'=> '0923', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'La Esperanza'],
         ['codigo'=> '0924', 'region' => '', 'codigo_depto' => '9', 'nombre' => 'Palestina de los Altos'],
         ['codigo'=> '1001', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Mazatenango'],
         ['codigo'=> '1002', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Cuyotenango'],
         ['codigo'=> '1003', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Francisco Zapotitlán'],
         ['codigo'=> '1004', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Bernardino'],
         ['codigo'=> '1005', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San José el Idolo'],
         ['codigo'=> '1006', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Santo Domingo Suchitepéquez'],
         ['codigo'=> '1007', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Lorenzo'],
         ['codigo'=> '1008', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Samayac'],
         ['codigo'=> '1009', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Pablo Jocopilas'],
         ['codigo'=> '1010', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Antonio Suchitepéquez'],
         ['codigo'=> '1011', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Miguel Panán'],
         ['codigo'=> '1012', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Gabriel'],
         ['codigo'=> '1013', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Chicacao'],
         ['codigo'=> '1014', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Patulul'],
         ['codigo'=> '1015', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Santa Bárbara'],
         ['codigo'=> '1016', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San Juan Bautista'],
         ['codigo'=> '1017', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Santo Tomás la Unión'],
         ['codigo'=> '1018', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Zunilito'],
         ['codigo'=> '1019', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Pueblo Nuevo'],
         ['codigo'=> '1020', 'region' => '', 'codigo_depto' => '10','nombre' =>  'Río Bravo'],
         ['codigo'=> '1021', 'region' => '', 'codigo_depto' => '10','nombre' =>  'San José La Máquina'],
         ['codigo'=> '1101', 'region' => '', 'codigo_depto' => '11','nombre' =>  'Retalhuleu'],
         ['codigo'=> '1102', 'region' => '', 'codigo_depto' => '11','nombre' =>  'San Sebastián'],
         ['codigo'=> '1103', 'region' => '', 'codigo_depto' => '11','nombre' =>  'Santa Cruz Muluá'],
         ['codigo'=> '1104', 'region' => '', 'codigo_depto' => '11','nombre' =>  'San Martín Zapotitlán'],
         ['codigo'=> '1105', 'region' => '', 'codigo_depto' => '11','nombre' =>  'San Felipe'],
         ['codigo'=> '1106', 'region' => '', 'codigo_depto' => '11','nombre' =>  'San Andrés Villa Seca'],
         ['codigo'=> '1107', 'region' => '', 'codigo_depto' => '11','nombre' =>  'Champerico'],
         ['codigo'=> '1108', 'region' => '', 'codigo_depto' => '11','nombre' =>  'Nuevo San Carlos'],
         ['codigo'=> '1109', 'region' => '', 'codigo_depto' => '11','nombre' =>  'El Asintal'],
         ['codigo'=> '1201', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Marcos'],
         ['codigo'=> '1202', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Pedro Sacatepéquez'],
         ['codigo'=> '1203', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Antonio Sacatepéquez'],
         ['codigo'=> '1204', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Comitancillo'],
         ['codigo'=> '1205', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Miguel Ixtahuacán'],
         ['codigo'=> '1206', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Concepción Tutuapa'],
         ['codigo'=> '1207', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Tacaná'],
         ['codigo'=> '1208', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Sibinal'],
         ['codigo'=> '1209', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Tajumulco'],
         ['codigo'=> '1210', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Tejutla'],
         ['codigo'=> '1211', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Rafael Pié de la Cuesta'],
         ['codigo'=> '1212', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Nuevo Progreso'],
         ['codigo'=> '1213', 'region' => '', 'codigo_depto' => '12','nombre' =>  'El Tumbador'],
         ['codigo'=> '1214', 'region' => '', 'codigo_depto' => '12','nombre' =>  'El Rodeo'],
         ['codigo'=> '1215', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Malacatán'],
         ['codigo'=> '1216', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Catarina'],
         ['codigo'=> '1217', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Ayutla'],
         ['codigo'=> '1218', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Ocós'],
         ['codigo'=> '1219', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Pablo'],
         ['codigo'=> '1220', 'region' => '', 'codigo_depto' => '12','nombre' =>  'El Quetzal'],
         ['codigo'=> '1221', 'region' => '', 'codigo_depto' => '12','nombre' =>  'La Reforma'],
         ['codigo'=> '1222', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Pajapita'],
         ['codigo'=> '1223', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Ixchiguán'],
         ['codigo'=> '1224', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San José Ojetenán'],
         ['codigo'=> '1225', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Cristóbal Cucho'],
         ['codigo'=> '1226', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Sipacapa'],
         ['codigo'=> '1227', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Esquipulas Palo Gordo'],
         ['codigo'=> '1228', 'region' => '', 'codigo_depto' => '12','nombre' =>  'Río Blanco'],
         ['codigo'=> '1229', 'region' => '', 'codigo_depto' => '12','nombre' =>  'San Lorenzo'],
         ['codigo'=> '1230', 'region' => '', 'codigo_depto' => '12','nombre' =>  'La Blanca'],
         ['codigo'=> '1301', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Huehuetenango'],
         ['codigo'=> '1302', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Chiantla'],
         ['codigo'=> '1303', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Malacatancito'],
         ['codigo'=> '1304', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Cuilco'],
         ['codigo'=> '1305', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Nentón'],
         ['codigo'=> '1306', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Pedro Necta'],
         ['codigo'=> '1307', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Jacaltenango'],
         ['codigo'=> '1308', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Soloma'],
         ['codigo'=> '1309', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Ixtahuacán'],
         ['codigo'=> '1310', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Santa Bárbara'],
         ['codigo'=> '1311', 'region' => '', 'codigo_depto' => '13','nombre' =>  'La Libertad'],
         ['codigo'=> '1312', 'region' => '', 'codigo_depto' => '13','nombre' =>  'La Democracia'],
         ['codigo'=> '1313', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Miguel Acatán'],
         ['codigo'=> '1314', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Rafael la Independencia'],
         ['codigo'=> '1315', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Todos Santos Cuchumatán'],
         ['codigo'=> '1316', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Juan Atitán'],
         ['codigo'=> '1317', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Santa Eulalia'],
         ['codigo'=> '1318', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Mateo Ixtatán'],
         ['codigo'=> '1319', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Colotenango'],
         ['codigo'=> '1320', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Sebastián Huehuetenango'],
         ['codigo'=> '1321', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Tectitán'],
         ['codigo'=> '1322', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Concepción Huista'],
         ['codigo'=> '1323', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Juan Ixcoy'],
         ['codigo'=> '1324', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Antonio Huista'],
         ['codigo'=> '1325', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Sebastián Coatán'],
         ['codigo'=> '1326', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Barillas'],
         ['codigo'=> '1327', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Aguacatán'],
         ['codigo'=> '1328', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Rafael Petzal'],
         ['codigo'=> '1329', 'region' => '', 'codigo_depto' => '13','nombre' =>  'San Gaspar Ixchil'],
         ['codigo'=> '1330', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Santiago Chimaltenango'],
         ['codigo'=> '1331', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Santa Ana Huista'],
         ['codigo'=> '1332', 'region' => '', 'codigo_depto' => '13','nombre' =>  'Unión Cantinil'],
         ['codigo'=> '1401', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Santa Cruz del Quiché'],
         ['codigo'=> '1402', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Chiché'],
         ['codigo'=> '1403', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Chinique'],
         ['codigo'=> '1404', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Zacualpa'],
         ['codigo'=> '1405', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Chajul'],
         ['codigo'=> '1406', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Chichicastenango'],
         ['codigo'=> '1407', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Patzité'],
         ['codigo'=> '1408', 'region' => '', 'codigo_depto' => '14','nombre' =>  'San Antonio Ilotenango'],
         ['codigo'=> '1409', 'region' => '', 'codigo_depto' => '14','nombre' =>  'San Pedro Jocopilas'],
         ['codigo'=> '1410', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Cunén'],
         ['codigo'=> '1411', 'region' => '', 'codigo_depto' => '14','nombre' =>  'San Juan Cotzal'],
         ['codigo'=> '1412', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Joyabaj'],
         ['codigo'=> '1413', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Nebaj'],
         ['codigo'=> '1414', 'region' => '', 'codigo_depto' => '14','nombre' =>  'San Andrés Sajcabajá'],
         ['codigo'=> '1415', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Uspantán'],
         ['codigo'=> '1416', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Sacapulas'],
         ['codigo'=> '1417', 'region' => '', 'codigo_depto' => '14','nombre' =>  'San Bartolomé Jocotenango'],
         ['codigo'=> '1418', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Canillá'],
         ['codigo'=> '1419', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Chicamán'],
         ['codigo'=> '1420', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Ixcán'],
         ['codigo'=> '1421', 'region' => '', 'codigo_depto' => '14','nombre' =>  'Pachalum'],
         ['codigo'=> '1501', 'region' => '', 'codigo_depto' => '15','nombre' =>  'Salamá'],
         ['codigo'=> '1502', 'region' => '', 'codigo_depto' => '15','nombre' =>  'San Miguel Chicaj'],
         ['codigo'=> '1503', 'region' => '', 'codigo_depto' => '15','nombre' =>  'Rabinal'],
         ['codigo'=> '1504', 'region' => '', 'codigo_depto' => '15','nombre' =>  'Cubulco'],
         ['codigo'=> '1505', 'region' => '', 'codigo_depto' => '15','nombre' =>  'Granados'],
         ['codigo'=> '1506', 'region' => '', 'codigo_depto' => '15','nombre' =>  'El Chol'],
         ['codigo'=> '1507', 'region' => '', 'codigo_depto' => '15','nombre' =>  'San Jerónimo'],
         ['codigo'=> '1508', 'region' => '', 'codigo_depto' => '15','nombre' =>  'Purulhá'],
         ['codigo'=> '1601', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Cobán'],
         ['codigo'=> '1602', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Santa Cruz Verapaz'],
         ['codigo'=> '1603', 'region' => '', 'codigo_depto' => '16','nombre' =>  'San Cristóbal Verapaz'],
         ['codigo'=> '1604', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Tactic'],
         ['codigo'=> '1605', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Tamahú'],
         ['codigo'=> '1606', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Tucurú'],
         ['codigo'=> '1607', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Panzós'],
         ['codigo'=> '1608', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Senahú'],
         ['codigo'=> '1609', 'region' => '', 'codigo_depto' => '16','nombre' =>  'San Pedro Carchá'],
         ['codigo'=> '1610', 'region' => '', 'codigo_depto' => '16','nombre' =>  'San Juan Chamelco'],
         ['codigo'=> '1611', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Lanquín'],
         ['codigo'=> '1612', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Cahabón'],
         ['codigo'=> '1613', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Chisec'],
         ['codigo'=> '1614', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Chahal'],
         ['codigo'=> '1615', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Fray Bartolomé de las Casas'],
         ['codigo'=> '1616', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Santa Catalina la Tinta'],
         ['codigo'=> '1617', 'region' => '', 'codigo_depto' => '16','nombre' =>  'Raxruhá'],
         ['codigo'=> '1701', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Flores'],
         ['codigo'=> '1702', 'region' => '', 'codigo_depto' => '17','nombre' =>  'San José'],
         ['codigo'=> '1703', 'region' => '', 'codigo_depto' => '17','nombre' =>  'San Benito'],
         ['codigo'=> '1704', 'region' => '', 'codigo_depto' => '17','nombre' =>  'San Andrés'],
         ['codigo'=> '1705', 'region' => '', 'codigo_depto' => '17','nombre' =>  'La Libertad'],
         ['codigo'=> '1706', 'region' => '', 'codigo_depto' => '17','nombre' =>  'San Francisco'],
         ['codigo'=> '1707', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Santa Ana'],
         ['codigo'=> '1708', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Dolores'],
         ['codigo'=> '1709', 'region' => '', 'codigo_depto' => '17','nombre' =>  'San Luis'],
         ['codigo'=> '1710', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Sayaxché'],
         ['codigo'=> '1711', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Melchor de Mencos'],
         ['codigo'=> '1712', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Poptún'],
         ['codigo'=> '1713', 'region' => '', 'codigo_depto' => '17','nombre' =>  'Las Cruces'],
         ['codigo'=> '1714', 'region' => '', 'codigo_depto' => '17','nombre' =>  'El Chal'],
         ['codigo'=> '1801', 'region' => '', 'codigo_depto' => '18','nombre' =>  'Puerto Barrios'],
         ['codigo'=> '1802', 'region' => '', 'codigo_depto' => '18','nombre' =>  'Livingston'],
         ['codigo'=> '1803', 'region' => '', 'codigo_depto' => '18','nombre' =>  'El Estor'],
         ['codigo'=> '1804', 'region' => '', 'codigo_depto' => '18','nombre' =>  'Morales'],
         ['codigo'=> '1805', 'region' => '', 'codigo_depto' => '18','nombre' =>  'Los Amates'],
         ['codigo'=> '1901', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Zacapa'],
         ['codigo'=> '1902', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Estanzuela'],
         ['codigo'=> '1903', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Río Hondo'],
         ['codigo'=> '1904', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Gualán'],
         ['codigo'=> '1905', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Teculután'],
         ['codigo'=> '1906', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Usumatlán'],
         ['codigo'=> '1907', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Cabañas'],
         ['codigo'=> '1908', 'region' => '', 'codigo_depto' => '19','nombre' =>  'San Diego'],
         ['codigo'=> '1909', 'region' => '', 'codigo_depto' => '19','nombre' =>  'La Unión'],
         ['codigo'=> '1910', 'region' => '', 'codigo_depto' => '19','nombre' =>  'Huité'],
         ['codigo'=> '1911', 'region' => '', 'codigo_depto' => '19','nombre' =>  'San Jorge'],
         ['codigo'=> '2001', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Chiquimula'],
         ['codigo'=> '2002', 'region' => '', 'codigo_depto' => '20','nombre' =>  'San José La Arada'],
         ['codigo'=> '2003', 'region' => '', 'codigo_depto' => '20','nombre' =>  'San Juan Ermita'],
         ['codigo'=> '2004', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Jocotán'],
         ['codigo'=> '2005', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Camotán'],
         ['codigo'=> '2006', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Olopa'],
         ['codigo'=> '2007', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Esquipulas'],
         ['codigo'=> '2008', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Concepción Las Minas'],
         ['codigo'=> '2009', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Quetzaltepeque'],
         ['codigo'=> '2010', 'region' => '', 'codigo_depto' => '20','nombre' =>  'San Jacinto'],
         ['codigo'=> '2011', 'region' => '', 'codigo_depto' => '20','nombre' =>  'Ipala'],
         ['codigo'=> '2101', 'region' => '', 'codigo_depto' => '21','nombre' =>  'Jalapa'],
         ['codigo'=> '2102', 'region' => '', 'codigo_depto' => '21','nombre' =>  'San Pedro Pinula'],
         ['codigo'=> '2103', 'region' => '', 'codigo_depto' => '21','nombre' =>  'San Luis Jilotepeque'],
         ['codigo'=> '2104', 'region' => '', 'codigo_depto' => '21','nombre' =>  'San Manuel Chaparrón'],
         ['codigo'=> '2105', 'region' => '', 'codigo_depto' => '21','nombre' =>  'San Carlos Alzatate'],
         ['codigo'=> '2106', 'region' => '', 'codigo_depto' => '21','nombre' =>  'Monjas'],
         ['codigo'=> '2107', 'region' => '', 'codigo_depto' => '21','nombre' =>  'Mataquescuintla'],
         ['codigo'=> '2201', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Jutiapa'],
         ['codigo'=> '2202', 'region' => '', 'codigo_depto' => '22','nombre' =>  'El Progreso'],
         ['codigo'=> '2203', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Santa Catarina Mita'],
         ['codigo'=> '2204', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Agua Blanca'],
         ['codigo'=> '2205', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Asunción Mita'],
         ['codigo'=> '2206', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Yupiltepeque'],
         ['codigo'=> '2207', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Atescatempa'],
         ['codigo'=> '2208', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Jerez'],
         ['codigo'=> '2209', 'region' => '', 'codigo_depto' => '22','nombre' =>  'El Adelanto'],
         ['codigo'=> '2210', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Zapotitlán'],
         ['codigo'=> '2211', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Comapa'],
         ['codigo'=> '2212', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Jalpatagua'],
         ['codigo'=> '2213', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Conguaco'],
         ['codigo'=> '2214', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Moyuta'],
         ['codigo'=> '2215', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Pasaco'],
         ['codigo'=> '2216', 'region' => '', 'codigo_depto' => '22','nombre' =>  'San José Acatempa'],
         ['codigo'=> '2217', 'region' => '', 'codigo_depto' => '22','nombre' =>  'Quesada'],
      ];

      foreach ($departamentos as $depto) {

         Departamento::updateOrCreate(
            ['codigo'  => $depto['codigo']],
            [
               'nombre'       => $depto['nombre'],
               'region'       => $depto['region'],
               'codigo_depto' => $depto['codigo_depto'],
               'estado'        => 1,
            ]
         );
      }
   }
}
